# Setup
title: dc143c
tagline: blog

url: https://dc143cDev.github.io
#paginate: 1
baseurl: ""
permalink: pretty

author:
  name: dc143c
  bio: Mobile App Developer<br>한 손에 들어오는 도구를 만듭니다.
  github: https://github.com/dc143cDev
  email: devc143c@gmail.com

# Gem
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts

# Custom vars
version: 3.0.0
