# Setup
title: dc143c
tagline: blog
url: https://dc143cDev.github.io
#paginate: 1
baseurl: ""
permalink: pretty

author:
  name: dc143c
  bio: 개발자이자 아마추어 작가입니다.<br>유용한 도구와 재밌는 이야기, 게임을 만드는 것에 관심이 있습니다.<br>모바일 앱 개발자로 커리어를 시작하여, Flutter의 한계를 뛰어넘는 작업에 도전중입니다.
  url: https://dc143cDev.github.io
  email: devc143c@gmail.com

# Gem
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts

# Custom vars
version: 3.0.0
