# Setup
title: dc143c
tagline: 블로그 설명
url: https://dc143cDev.github.io
paginate: 1
baseurl: ""
permalink: pretty

author:
  name: dc143c
  bio: 블로그 설명
  url: https://dc143cDev.github.io
  email: devc143c@gmail.com

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts

# Custom vars
version: 3.0.0
